name: Development workflow

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: cd casnode-website &&  npm install && npm run build && cd ..

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=casnode-website/build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
