name: test ci

on:
  push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: Test step 1
        run: |
          mkdir xbqtest233
          ls